export default [
  {
    files: ["js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        caches: "readonly",
        self: "readonly",
        fetch: "readonly",
        clearTimeout: "readonly",
        setTimeout: "readonly",
        structuredClone: "readonly",
        getComputedStyle: "readonly",
        CSS: "readonly",
        DOMException: "readonly",
        FileReader: "readonly",
        Image: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        HTMLDialogElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLMetaElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLButtonElement: "readonly",
        URL: "readonly",
        performance: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "error",
      "prefer-const": "warn",
    },
  },
];
