export const THEME_PRESETS = [
  {
    id: 'blueprint',
    label: 'Blueprint',
    icon: 'bi-moon-stars',
    mode: 'dark',
    color: '#0f172a',
    tokens: {
      surface: '#131d2e',
      'surface-muted': '#172338',
      'surface-raised': '#101826',
      border: '#2b3a52',
      text: '#e2e8f0',
      'text-muted': '#94a3b8',
      accent: '#60a5fa',
      'accent-contrast': '#132238',
      'focus-ring': '#93c5fd',
      danger: '#fecaca',
      success: '#86efac',
      bg: '#0f172a',
      'grid-dot': '#23324a',
      panel: 'color-mix(in srgb, var(--surface-raised) 98%, transparent)',
      'toolbar-bg': 'rgba(16, 24, 38, 0.82)',
      'panel-border': 'var(--border)',
      muted: 'var(--text-muted)',
      edge: '#5c779a',
      'edge-selected': 'var(--focus-ring)',
      'surface-soft': 'var(--surface-muted)',
      'danger-soft': '#3c1a20',
      'danger-border': '#7f1d1d',
      'danger-text': 'var(--danger)',
      'draft-stroke': '#9fb2cc',
      'endpoint-stroke': '#9fb2cc',
      'endpoint-fill': '#111d2f',
      'overlay-shadow': '0 12px 30px rgba(0, 0, 0, 0.45)',
      'node-shadow': '0 10px 26px rgba(0, 0, 0, 0.42)',
    },
  },
  {
    id: 'fjord',
    label: 'Fjord',
    icon: 'bi-water',
    mode: 'dark',
    color: '#0d1b24',
    tokens: {
      bg: '#0d1b24',
      surface: '#122630',
      'surface-muted': '#18323d',
      'surface-raised': '#10212a',
      border: '#2f4a59',
      text: '#deebf0',
      'text-muted': '#8da4af',
      accent: '#78b8c9',
      'accent-contrast': '#10242d',
      'focus-ring': '#9ad5e4',
      danger: '#ffcdc4',
      success: '#8fe0b1',
      'grid-dot': '#27404d',
      panel: 'color-mix(in srgb, var(--surface-raised) 98%, transparent)',
      'toolbar-bg': 'rgba(16, 33, 42, 0.84)',
      'panel-border': 'var(--border)',
      muted: 'var(--text-muted)',
      edge: '#5f8797',
      'edge-selected': 'var(--focus-ring)',
      'surface-soft': 'var(--surface-muted)',
      'danger-soft': '#432329',
      'danger-border': '#8f3b43',
      'danger-text': 'var(--danger)',
      'draft-stroke': '#96b8c4',
      'endpoint-stroke': '#96b8c4',
      'endpoint-fill': '#11212a',
      'overlay-shadow': '0 12px 30px rgba(0, 0, 0, 0.42)',
      'node-shadow': '0 10px 26px rgba(0, 0, 0, 0.4)',
    },
  },
  {
    id: 'slate',
    label: 'Slate',
    icon: 'bi-cloud-fog2',
    mode: 'light',
    color: '#e6e9ed',
    tokens: {
      surface: '#f6f7f8',
      'surface-muted': '#eef0f2',
      'surface-raised': '#fbfcfc',
      border: '#ccd2d8',
      text: '#29313a',
      'text-muted': '#66727f',
      accent: '#5f748d',
      'accent-contrast': '#edf2f7',
      'focus-ring': '#4c6279',
      danger: '#b23a3a',
      'danger-soft': '#f9ecec',
      'danger-border': '#e8bcbc',
      success: '#356b59',
      bg: '#e6e9ed',
      'grid-dot': '#c7ced6',
      panel: 'color-mix(in srgb, var(--surface-raised) 98%, transparent)',
      'toolbar-bg': 'rgba(247, 248, 249, 0.82)',
      'panel-border': 'var(--border)',
      muted: 'var(--text-muted)',
      edge: '#8f9ba8',
      'edge-selected': 'var(--focus-ring)',
      'surface-soft': 'var(--surface-muted)',
      'danger-text': 'var(--danger)',
      'draft-stroke': '#72808f',
      'endpoint-stroke': '#96a4b4',
      'endpoint-fill': '#f9fbfc',
      'overlay-shadow': '0 10px 28px rgba(31, 41, 55, 0.1)',
      'node-shadow': '0 8px 22px rgba(31, 41, 55, 0.08)',
    },
  },
  {
    id: 'paper',
    label: 'Paper',
    icon: 'bi-sun',
    mode: 'light',
    color: '#f4f7fb',
    tokens: {
      surface: '#ffffff',
      'surface-muted': '#f5f7fb',
      'surface-raised': '#ffffff',
      border: '#d9e1ec',
      text: '#182330',
      'text-muted': '#607185',
      accent: '#2563eb',
      'accent-contrast': '#eef4ff',
      'focus-ring': '#1d4ed8',
      danger: '#b42318',
      'danger-soft': '#fff1f2',
      'danger-border': '#fecaca',
      success: '#1f7a4d',
      bg: '#f4f7fb',
      'grid-dot': '#d5deea',
      panel: 'color-mix(in srgb, var(--surface-raised) 98%, transparent)',
      'toolbar-bg': 'rgba(255, 255, 255, 0.82)',
      'panel-border': 'var(--border)',
      muted: 'var(--text-muted)',
      edge: '#92a8c5',
      'edge-selected': 'var(--focus-ring)',
      'surface-soft': 'var(--surface-muted)',
      'danger-text': 'var(--danger)',
      'draft-stroke': '#6b7f99',
      'endpoint-stroke': '#8ea3c1',
      'endpoint-fill': '#f8fbff',
      'overlay-shadow': '0 10px 30px rgba(15, 23, 42, 0.1)',
      'node-shadow': '0 8px 24px rgba(15, 23, 42, 0.08)',
    },
  },
  {
    id: 'ember',
    label: 'Ember',
    icon: 'bi-brightness-alt-high',
    mode: 'light',
    color: '#f3eadf',
    tokens: {
      surface: '#fff9f2',
      'surface-muted': '#f6eee3',
      'surface-raised': '#fffcf7',
      border: '#dfcfbf',
      text: '#3b3028',
      'text-muted': '#7a685b',
      accent: '#c36d3e',
      'accent-contrast': '#fff1e8',
      'focus-ring': '#a8572c',
      danger: '#b93d2f',
      'danger-soft': '#fff0ec',
      'danger-border': '#f2c3ba',
      success: '#3f7a52',
      bg: '#f3eadf',
      'grid-dot': '#d9cabb',
      panel: 'color-mix(in srgb, var(--surface-raised) 98%, transparent)',
      'toolbar-bg': 'rgba(255, 249, 242, 0.84)',
      'panel-border': 'var(--border)',
      muted: 'var(--text-muted)',
      edge: '#ae8a72',
      'edge-selected': 'var(--focus-ring)',
      'surface-soft': 'var(--surface-muted)',
      'danger-text': 'var(--danger)',
      'draft-stroke': '#8c715f',
      'endpoint-stroke': '#b79a85',
      'endpoint-fill': '#fffdfa',
      'overlay-shadow': '0 10px 28px rgba(59, 48, 40, 0.1)',
      'node-shadow': '0 8px 22px rgba(59, 48, 40, 0.08)',
    },
  },
  {
    id: 'chalkboard',
    label: 'Chalkboard',
    icon: 'bi-circle-half',
    mode: 'dark',
    color: '#121315',
    tokens: {
      bg: '#121315',
      surface: '#181a1d',
      'surface-muted': '#1e2125',
      'surface-raised': '#16181b',
      border: '#30343a',
      text: '#eceff2',
      'text-muted': '#9ca3ad',
      accent: '#b7c2cf',
      'accent-contrast': '#1b1e22',
      'focus-ring': '#d8e0e8',
      danger: '#ffd0cb',
      success: '#98ddb1',
      'grid-dot': '#272b30',
      panel: 'color-mix(in srgb, var(--surface-raised) 98%, transparent)',
      'toolbar-bg': 'rgba(22, 24, 27, 0.84)',
      'panel-border': 'var(--border)',
      muted: 'var(--text-muted)',
      edge: '#727b86',
      'edge-selected': 'var(--focus-ring)',
      'surface-soft': 'var(--surface-muted)',
      'danger-soft': '#402326',
      'danger-border': '#89474c',
      'danger-text': 'var(--danger)',
      'draft-stroke': '#a2adb8',
      'endpoint-stroke': '#a2adb8',
      'endpoint-fill': '#181a1d',
      'overlay-shadow': '0 12px 30px rgba(0, 0, 0, 0.48)',
      'node-shadow': '0 10px 26px rgba(0, 0, 0, 0.44)',
    },
  },
  {
    id: 'citrine',
    label: 'Citrine',
    icon: 'bi-sunrise',
    mode: 'light',
    color: '#fbf6e8',
    tokens: {
      surface: '#fffdfa',
      'surface-muted': '#f5efe1',
      'surface-raised': '#fffefb',
      border: '#decdaa',
      text: '#382918',
      'text-muted': '#7d6a4a',
      accent: '#b8891f',
      'accent-contrast': '#fff5d8',
      'focus-ring': '#9f7315',
      danger: '#b63a24',
      'danger-soft': '#fff0eb',
      'danger-border': '#f0c1b1',
      success: '#3d7b4f',
      bg: '#fbf6e8',
      'grid-dot': '#e2d4b8',
      panel: 'color-mix(in srgb, var(--surface-raised) 98%, transparent)',
      'toolbar-bg': 'rgba(255, 253, 250, 0.84)',
      'panel-border': 'var(--border)',
      muted: 'var(--text-muted)',
      edge: '#b79f70',
      'edge-selected': 'var(--focus-ring)',
      'surface-soft': 'var(--surface-muted)',
      'danger-text': 'var(--danger)',
      'draft-stroke': '#8d7a57',
      'endpoint-stroke': '#bda77a',
      'endpoint-fill': '#fffdf8',
      'overlay-shadow': '0 10px 28px rgba(56, 41, 24, 0.1)',
      'node-shadow': '0 8px 22px rgba(56, 41, 24, 0.08)',
    },
  },
  {
    id: 'canopy',
    label: 'Canopy',
    icon: 'bi-tree',
    mode: 'light',
    color: '#eef4ec',
    tokens: {
      surface: '#f9fcf8',
      'surface-muted': '#edf3ec',
      'surface-raised': '#fcfefb',
      border: '#c8d8ca',
      text: '#203128',
      'text-muted': '#5e7666',
      accent: '#4f7d5f',
      'accent-contrast': '#ecf6ef',
      'focus-ring': '#3e694e',
      danger: '#b64134',
      'danger-soft': '#fcede9',
      'danger-border': '#eabbb3',
      success: '#34744d',
      bg: '#eef4ec',
      'grid-dot': '#cfdbcf',
      panel: 'color-mix(in srgb, var(--surface-raised) 98%, transparent)',
      'toolbar-bg': 'rgba(249, 252, 248, 0.84)',
      'panel-border': 'var(--border)',
      muted: 'var(--text-muted)',
      edge: '#88a18e',
      'edge-selected': 'var(--focus-ring)',
      'surface-soft': 'var(--surface-muted)',
      'danger-text': 'var(--danger)',
      'draft-stroke': '#748b79',
      'endpoint-stroke': '#93aa98',
      'endpoint-fill': '#fbfefb',
      'overlay-shadow': '0 10px 28px rgba(32, 49, 40, 0.1)',
      'node-shadow': '0 8px 22px rgba(32, 49, 40, 0.08)',
    },
  },
  {
    id: 'tidepool',
    label: 'Tidepool',
    icon: 'bi-water',
    mode: 'dark',
    color: '#0f2329',
    tokens: {
      bg: '#0f2329',
      surface: '#123039',
      'surface-muted': '#183d47',
      'surface-raised': '#102a32',
      border: '#2b5661',
      text: '#ddf0f1',
      'text-muted': '#91adb2',
      accent: '#59b7bf',
      'accent-contrast': '#10292f',
      'focus-ring': '#82d6dc',
      danger: '#ffd1c4',
      'danger-soft': '#472722',
      'danger-border': '#91544a',
      success: '#90e0be',
      'grid-dot': '#244750',
      panel: 'color-mix(in srgb, var(--surface-raised) 98%, transparent)',
      'toolbar-bg': 'rgba(16, 42, 50, 0.84)',
      'panel-border': 'var(--border)',
      muted: 'var(--text-muted)',
      edge: '#5f949b',
      'edge-selected': 'var(--focus-ring)',
      'surface-soft': 'var(--surface-muted)',
      'danger-text': 'var(--danger)',
      'draft-stroke': '#8bb8bd',
      'endpoint-stroke': '#8bb8bd',
      'endpoint-fill': '#112d35',
      'overlay-shadow': '0 12px 30px rgba(0, 0, 0, 0.42)',
      'node-shadow': '0 10px 26px rgba(0, 0, 0, 0.4)',
    },
  },
  {
    id: 'dusk',
    label: 'Dusk',
    icon: 'bi-moon-stars',
    mode: 'dark',
    color: '#16182b',
    tokens: {
      bg: '#16182b',
      surface: '#1a1d33',
      'surface-muted': '#22263f',
      'surface-raised': '#171a2f',
      border: '#3a4164',
      text: '#e8eaf7',
      'text-muted': '#a1a7c8',
      accent: '#7f8ff3',
      'accent-contrast': '#171d37',
      'focus-ring': '#aab4ff',
      danger: '#ffd1d1',
      'danger-soft': '#43232e',
      'danger-border': '#8d4d60',
      success: '#93dfbf',
      'grid-dot': '#2e3454',
      panel: 'color-mix(in srgb, var(--surface-raised) 98%, transparent)',
      'toolbar-bg': 'rgba(23, 26, 47, 0.84)',
      'panel-border': 'var(--border)',
      muted: 'var(--text-muted)',
      edge: '#6c76ad',
      'edge-selected': 'var(--focus-ring)',
      'surface-soft': 'var(--surface-muted)',
      'danger-text': 'var(--danger)',
      'draft-stroke': '#a1a9d8',
      'endpoint-stroke': '#a1a9d8',
      'endpoint-fill': '#191c31',
      'overlay-shadow': '0 12px 30px rgba(0, 0, 0, 0.46)',
      'node-shadow': '0 10px 26px rgba(0, 0, 0, 0.42)',
    },
  },
];

export const THEME_PRESET_IDS = THEME_PRESETS.map((theme) => theme.id);

const THEME_PRESET_MAP = new Map(THEME_PRESETS.map((theme) => [theme.id, theme]));

export function getThemePresetById(themeId) {
  return THEME_PRESET_MAP.get(themeId) ?? THEME_PRESET_MAP.get('blueprint');
}

export function isValidThemePresetId(themeId) {
  return typeof themeId === 'string' && THEME_PRESET_MAP.has(themeId);
}

export function sanitizeEnabledThemePresetIds(themeIds) {
  const input = Array.isArray(themeIds) ? themeIds : THEME_PRESET_IDS;
  const seen = new Set();
  const sanitized = [];
  input.forEach((themeId) => {
    if (!isValidThemePresetId(themeId) || seen.has(themeId)) return;
    seen.add(themeId);
    sanitized.push(themeId);
  });
  return sanitized.length ? sanitized : [...THEME_PRESET_IDS];
}

export function getThemePresetSequence(enabledThemeIds = null) {
  if (enabledThemeIds === null) {
    return [...THEME_PRESET_IDS];
  }
  return sanitizeEnabledThemePresetIds(enabledThemeIds);
}

