export const SHORTCUT_CATALOG = [
  {
    id: 'new-graph',
    keys: ['Ctrl/Cmd + Shift + H'],
    title: 'New hypernode',
    description: 'Creates a new hypernode file.',
    searchTokens: ['new', 'graph', 'file', 'create'],
  },
  {
    id: 'open-graph',
    keys: ['Ctrl/Cmd + O'],
    title: 'Open hypernode',
    description: 'Opens a hypernode file.',
    searchTokens: ['open', 'graph', 'file', 'import'],
  },
  {
    id: 'add-node',
    keys: ['N'],
    title: 'Add node',
    description: 'Creates a new node.',
    searchTokens: ['node', 'create', 'text', 'toolbar', 'pointer', 'mouse', 'cursor'],
  },
  {
    id: 'add-image-node',
    keys: ['I'],
    title: 'Add image node',
    description: 'Opens the image picker and adds a new image node.',
    searchTokens: ['image', 'media', 'create', 'toolbar'],
  },
  {
    id: 'draw-frame',
    keys: ['F'],
    title: 'Toggle frame draw',
    description: 'Turns frame drawing mode on or off.',
    searchTokens: ['frame', 'draw', 'toggle', 'group'],
  },
  {
    id: 'delete-selection',
    keys: ['Delete', 'Backspace'],
    title: 'Delete selection',
    description: 'Deletes the selected node or edge.',
    searchTokens: ['delete', 'selected', 'node', 'edge', 'remove'],
  },
  {
    id: 'create-linked-node',
    keys: ['Ctrl/Cmd + Shift + Enter'],
    title: 'Create linked node',
    description: 'Adds a new node linked from the current selection.',
    searchTokens: ['linked', 'node', 'create', 'connection', 'follow-up'],
  },
  {
    id: 'directional-navigation',
    keys: ['Ctrl/Cmd + Arrow'],
    title: 'Directional navigation',
    description: 'Follows a connected node in that direction, otherwise the nearest candidate.',
    searchTokens: ['up', 'down', 'left', 'right', 'follow', 'connected', 'graph'],
  },
  {
    id: 'undo',
    keys: ['Ctrl/Cmd + Z'],
    title: 'Undo',
    description: 'Reverts the last change.',
    searchTokens: ['undo', 'revert', 'history'],
  },
  {
    id: 'redo',
    keys: ['Ctrl/Cmd + Y', 'Ctrl/Cmd + Shift + Z'],
    title: 'Redo',
    description: 'Reapplies the last undone change.',
    searchTokens: ['redo', 'history', 'repeat'],
  },
  {
    id: 'save',
    keys: ['Ctrl/Cmd + S'],
    title: 'Save hypernode file',
    description: 'Saves the current hypernode file.',
    searchTokens: ['save', 'file', 'export'],
  },
  {
    id: 'reset-view',
    keys: ['Ctrl/Cmd + 0'],
    title: 'Reset view',
    description: 'Resets pan and zoom to the default canvas view.',
    searchTokens: ['reset', 'view', 'zoom', 'pan', 'center'],
  },
  {
    id: 'toggle-editor',
    keys: ['Ctrl/Cmd + Enter'],
    title: 'Toggle editor',
    description: 'Toggles the selected node or frame editor.',
    searchTokens: ['edit', 'editor', 'node', 'frame', 'read'],
  },
  {
    id: 'toggle-focus',
    keys: ['Ctrl/Cmd + Alt + Enter'],
    title: 'Toggle focus mode',
    description: 'Enters or exits focus mode for the selected node.',
    searchTokens: ['focus', 'fullscreen', 'node'],
  },
  {
    id: 'add-to-selection',
    keys: ['Ctrl/Cmd + Click'],
    title: 'Add to selection',
    description: 'Adds a node to the current multi-selection.',
    searchTokens: ['multi-select', 'selection', 'additive', 'node'],
  },
  {
    id: 'open-settings',
    keys: ['Ctrl/Cmd + ,'],
    title: 'Open settings',
    description: 'Opens the hypernode settings dialog.',
    searchTokens: ['settings', 'preferences', 'dialog'],
  },
  {
    id: 'open-shortcuts',
    keys: ['Ctrl/Cmd + /'],
    title: 'Open keyboard shortcuts',
    description: 'Opens the keyboard shortcuts dialog.',
    searchTokens: ['shortcuts', 'help', 'keys', 'dialog'],
  },
  {
    id: 'toggle-theme',
    keys: ['T'],
    title: 'Toggle document theme',
    description: 'Cycles through the curated theme presets.',
    searchTokens: ['theme', 'appearance', 'blueprint', 'fjord', 'slate', 'paper', 'ember', 'chalkboard', 'preset'],
  },
  {
    id: 'open-about',
    keys: ['Shift + ?'],
    title: 'Open about',
    description: 'Opens the about dialog and guide.',
    searchTokens: ['about', 'help', 'guide', 'info'],
  },
  {
    id: 'cancel-exit',
    keys: ['Esc'],
    title: 'Cancel or exit',
    description: 'Exits focus or edit mode, cancels connect or frame draw, or clears selection.',
    searchTokens: ['escape', 'cancel', 'clear', 'selection', 'frame', 'draw', 'connect'],
  },
];

export const TOOLBAR_SHORTCUTS = {
  'new-graph-btn': { label: 'New file', shortcut: 'Ctrl/Cmd+Shift+H' },
  'add-node-btn': { label: 'Add node', shortcut: 'N' },
  'add-image-btn': { label: 'Add image node', shortcut: 'I' },
  'add-frame-btn': { label: 'Draw frame', shortcut: 'F' },
  'open-graph-btn': { label: 'Open file', shortcut: 'Ctrl/Cmd+O' },
  'save-graph-btn': { label: 'Save file', shortcut: 'Ctrl/Cmd+S' },
  'undo-btn': { label: 'Undo', shortcut: 'Ctrl/Cmd+Z' },
  'redo-btn': { label: 'Redo', shortcut: 'Ctrl/Cmd+Y' },
  'reset-view-btn': { label: 'Reset view', shortcut: 'Ctrl/Cmd+0' },
  'settings-btn': { label: 'Settings', shortcut: 'Ctrl/Cmd+,' },
  'shortcuts-btn': { label: 'Shortcuts', shortcut: 'Ctrl/Cmd+/' },
  'about-btn': { label: 'About', shortcut: 'Shift+?' },
};
